package GUI;
/**
*
* @author preethi
*/
public class AccountPage extends javax.swing.JFrame {

   /**
    * Creates new form AccountPage
    */
   public AccountPage() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       panelGradient1 = new GUI.PanelGradient();
       myAccountLabel = new javax.swing.JLabel();
       firstNameLabel = new javax.swing.JLabel();
       lastNameLabel = new javax.swing.JLabel();
       usernameLabel = new javax.swing.JLabel();
       emailLabel = new javax.swing.JLabel();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       panelGradient1.setColorPrimario(new java.awt.Color(159, 234, 234));
       panelGradient1.setColorSecundario(new java.awt.Color(13, 165, 165));

       myAccountLabel.setFont(new java.awt.Font("Canela", 1, 70)); // NOI18N
       myAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
       myAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       myAccountLabel.setText("My Account:");

       firstNameLabel.setFont(new java.awt.Font("Canela", 1, 30)); // NOI18N
       firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
       firstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       firstNameLabel.setText("First Name");

       lastNameLabel.setFont(new java.awt.Font("Canela", 1, 30)); // NOI18N
       lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
       lastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       lastNameLabel.setText("Last Name");

       usernameLabel.setFont(new java.awt.Font("Canela", 1, 30)); // NOI18N
       usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
       usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       usernameLabel.setText("Username");

       emailLabel.setFont(new java.awt.Font("Canela", 1, 30)); // NOI18N
       emailLabel.setForeground(new java.awt.Color(255, 255, 255));
       emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       emailLabel.setText("Email");

       panelGradient1.setLayer(myAccountLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
       panelGradient1.setLayer(firstNameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
       panelGradient1.setLayer(lastNameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
       panelGradient1.setLayer(usernameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
       panelGradient1.setLayer(emailLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

       javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
       panelGradient1.setLayout(panelGradient1Layout);
       panelGradient1Layout.setHorizontalGroup(
           panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(panelGradient1Layout.createSequentialGroup()
               .addGap(163, 163, 163)
               .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(myAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(panelGradient1Layout.createSequentialGroup()
                       .addGap(12, 12, 12)
                       .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(usernameLabel)
                           .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(firstNameLabel))))
               .addContainerGap(860, Short.MAX_VALUE))
       );
       panelGradient1Layout.setVerticalGroup(
           panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(panelGradient1Layout.createSequentialGroup()
               .addGap(111, 111, 111)
               .addComponent(myAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(288, Short.MAX_VALUE))
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );

       pack();
   }// </editor-fold>                        

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new AccountPage().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JLabel emailLabel;
   private javax.swing.JLabel firstNameLabel;
   private javax.swing.JLabel lastNameLabel;
   private javax.swing.JLabel myAccountLabel;
   private GUI.PanelGradient panelGradient1;
   private javax.swing.JLabel usernameLabel;
   // End of variables declaration                   
}