package GUI;

import java.awt.Color;
import java.awt.Font;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.table.JTableHeader;

/**
 *
 * @author preethi
 */
public class CreateSchedule extends javax.swing.JFrame {

    /**
     * Creates new form CreateSchedule
     */
    public CreateSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelGradient1 = new GUI.PanelGradient();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGradient1.setColorPrimario(new java.awt.Color(159, 234, 234));
        panelGradient1.setColorSecundario(new java.awt.Color(13, 165, 165));

        //jTable1.setFont(new Font("Canela", 1, 10));
        JTableHeader tableHeader = jTable1.getTableHeader();
        Font headerFont = new Font("Canela", 1, 14);
        tableHeader.setFont(headerFont);
        jTable1.setFont(new java.awt.Font("Canela", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12 AM", null, null, null, null, null, null, null},
                {"1 AM", null, null, null, null, null, null, null},
                {"2 AM", null, null, null, null, null, null, null},
                {"3 AM", null, null, null, null, null, null, null},
                {"4 AM", null, null, null, null, null, null, null},
                {"5 AM", null, null, null, null, null, null, null},
                {"6 AM", null, null, null, null, null, null, null},
                {"7 AM", null, null, null, null, null, null, null},
                {"8 AM", null, null, null, null, null, null, null},
                {"9 AM", null, null, null, null, null, null, null},
                {"10 AM", null, null, null, null, null, null, null},
                {"11 AM", null, null, null, null, null, null, null},
                {"12 PM", null, null, null, null, null, null, null},
                {"1 PM", null, null, null, null, null, null, null},
                {"2 PM", null, null, null, null, null, null, null},
                {"3 PM", null, null, null, null, null, null, null},
                {"4 PM", null, null, null, null, null, null, null},
                {"5 PM", null, null, null, null, null, null, null},
                {"6 PM", null, null, null, null, null, null, null},
                {"7 PM", null, null, null, null, null, null, null},
                {"8 PM", null, null, null, null, null, null, null},
                {"9 PM", null, null, null, null, null, null, null},
                {"10 PM", null, null, null, null, null, null, null},
                {"11 PM", null, null, null, null, null, null, null}
            },
            new String [] {
                    "", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
            jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTable1.setIntercellSpacing(new java.awt.Dimension(10, 10));
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        panelGradient1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 30, 1360, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, 1443, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private GUI.PanelGradient panelGradient1;
    // End of variables declaration                   
}

class timeButton extends JFrame {
	
	private Color color;
	private int column;
	private int row;
}

